name: Computational Research Workflows Homework
on: [push]
jobs:
  tests:
    runs-on: ubuntu
    container: pachchek/jhale-computational-workflows-homework:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run test
        run: |
          py.test
